/**
 * Every top-level domain anybody can register, most used first.
 *
 * Generated — do not edit by hand. Run \`node scripts/generate-tlds.mjs\` to
 * refresh it, and read that script for where each part comes from.
 *
 * IANA root zone version 2026090701: 1438 TLDs exist, 379 of them
 * are brand registries, dead contracts or reserved, leaving 1059 to choose
 * from. 854 appear somewhere in the Tranco top million and are ordered by how
 * often; the remainder never appear and follow alphabetically.
 *
 * Each entry is the TLD as it appears in a hostname, optionally followed by
 * the Unicode form of an internationalised one: 'xn--fiqs8s' is what the
 * request is made against, '中国' is what somebody would search for.
 */

/** [tld, unicodeLabel?] */
export type TldEntry = readonly [string] | readonly [string, string];

export const ALL_TLDS: readonly TldEntry[] = [
    ['com'],
    ['net'],
    ['org'],
    ['ru'],
    ['uk'],
    ['de'],
    ['nl'],
    ['br'],
    ['jp'],
    ['it'],
    ['in'],
    ['fr'],
    ['cn'],
    ['io'],
    ['pl'],
    ['au'],
    ['co'],
    ['xyz'],
    ['eu'],
    ['ca'],
    ['cc'],
    ['es'],
    ['info'],
    ['shop'],
    ['top'],
    ['online'],
    ['id'],
    ['cz'],
    ['ua'],
    ['kr'],
    ['ro'],
    ['ch'],
    ['app'],
    ['site'],
    ['ai'],
    ['gr'],
    ['se'],
    ['mx'],
    ['be'],
    ['us'],
    ['ar'],
    ['ir'],
    ['at'],
    ['tr'],
    ['hu'],
    ['me'],
    ['za'],
    ['tw'],
    ['vn'],
    ['tv'],
    ['pro'],
    ['cl'],
    ['cloud'],
    ['biz'],
    ['vip'],
    ['casino'],
    ['fi'],
    ['dk'],
    ['live'],
    ['pt'],
    ['sk'],
    ['pk'],
    ['no'],
    ['store'],
    ['il'],
    ['nz'],
    ['my'],
    ['cfd'],
    ['club'],
    ['dev'],
    ['tech'],
    ['kz'],
    ['space'],
    ['ie'],
    ['ph'],
    ['by'],
    ['pe'],
    ['bg'],
    ['click'],
    ['hr'],
    ['lt'],
    ['rs'],
    ['fun'],
    ['su'],
    ['buzz'],
    ['th'],
    ['one'],
    ['sg'],
    ['hk'],
    ['link'],
    ['to'],
    ['win'],
    ['lv'],
    ['lol'],
    ['si'],
    ['gg'],
    ['ee'],
    ['ng'],
    ['ae'],
    ['mobi'],
    ['icu'],
    ['bd'],
    ['uz'],
    ['bet'],
    ['blog'],
    ['ma'],
    ['life'],
    ['ec'],
    ['sa'],
    ['az'],
    ['games'],
    ['ke'],
    ['lk'],
    ['network'],
    ['asia'],
    ['uy'],
    ['work'],
    ['xn--p1ai', 'рф'],
    ['news'],
    ['world'],
    ['ge'],
    ['is'],
    ['md'],
    ['media'],
    ['lat'],
    ['digital'],
    ['wiki'],
    ['cat'],
    ['art'],
    ['ink'],
    ['ws'],
    ['cyou'],
    ['website'],
    ['am'],
    ['fm'],
    ['eg'],
    ['today'],
    ['ba'],
    ['team'],
    ['tn'],
    ['py'],
    ['host'],
    ['pw'],
    ['mk'],
    ['im'],
    ['global'],
    ['name'],
    ['run'],
    ['nu'],
    ['xxx'],
    ['cam'],
    ['fit'],
    ['do'],
    ['kg'],
    ['lu'],
    ['sh'],
    ['video'],
    ['np'],
    ['chat'],
    ['st'],
    ['ve'],
    ['social'],
    ['gt'],
    ['tz'],
    ['services'],
    ['zone'],
    ['game'],
    ['best'],
    ['cr'],
    ['dz'],
    ['plus'],
    ['travel'],
    ['la'],
    ['pics'],
    ['bo'],
    ['group'],
    ['cy'],
    ['systems'],
    ['guru'],
    ['al'],
    ['bz'],
    ['mom'],
    ['tools'],
    ['baby'],
    ['cx'],
    ['ac'],
    ['love'],
    ['ly'],
    ['mn'],
    ['rest'],
    ['so'],
    ['jo'],
    ['li'],
    ['aero'],
    ['sv'],
    ['help'],
    ['moe'],
    ['ltd'],
    ['bio'],
    ['qa'],
    ['ug'],
    ['qpon'],
    ['autos'],
    ['center'],
    ['stream'],
    ['re'],
    ['pa'],
    ['city'],
    ['coop'],
    ['gh'],
    ['page'],
    ['quest'],
    ['tokyo'],
    ['bond'],
    ['studio'],
    ['solutions'],
    ['tube'],
    ['et'],
    ['pub'],
    ['rocks'],
    ['eus'],
    ['hn'],
    ['onl'],
    ['email'],
    ['fans'],
    ['wtf'],
    ['fyi'],
    ['health'],
    ['watch'],
    ['zw'],
    ['africa'],
    ['ag'],
    ['porn'],
    ['market'],
    ['ms'],
    ['mz'],
    ['ovh'],
    ['beauty'],
    ['design'],
    ['cm'],
    ['iq'],
    ['mt'],
    ['ninja'],
    ['red'],
    ['vc'],
    ['software'],
    ['ci'],
    ['zm'],
    ['cv'],
    ['finance'],
    ['homes'],
    ['ao'],
    ['cash'],
    ['om'],
    ['ps'],
    ['tj'],
    ['company'],
    ['skin'],
    ['uno'],
    ['bid'],
    ['land'],
    ['kh'],
    ['now'],
    ['trade'],
    ['bar'],
    ['cafe'],
    ['care'],
    ['ni'],
    ['jobs'],
    ['cool'],
    ['rw'],
    ['casa'],
    ['forum'],
    ['education'],
    ['hosting'],
    ['cu'],
    ['works'],
    ['sn'],
    ['agency'],
    ['kw'],
    ['study'],
    ['money'],
    ['domains'],
    ['mu'],
    ['community'],
    ['mm'],
    ['tel'],
    ['press'],
    ['academy'],
    ['beer'],
    ['direct'],
    ['men'],
    ['sx'],
    ['codes'],
    ['inc'],
    ['support'],
    ['day'],
    ['events'],
    ['lb'],
    ['sc'],
    ['bank'],
    ['tm'],
    ['expert'],
    ['hair'],
    ['download'],
    ['energy'],
    ['blue'],
    ['exchange'],
    ['rodeo'],
    ['school'],
    ['surf'],
    ['kim'],
    ['mv'],
    ['na'],
    ['ooo'],
    ['show'],
    ['swiss'],
    ['technology'],
    ['ad'],
    ['guide'],
    ['ing'],
    ['mo'],
    ['mov'],
    ['mw'],
    ['sy'],
    ['gold'],
    ['party'],
    ['tt'],
    ['date'],
    ['gd'],
    ['yachts'],
    ['vg'],
    ['berlin'],
    ['gs'],
    ['rip'],
    ['vin'],
    ['af'],
    ['bh'],
    ['bike'],
    ['earth'],
    ['report'],
    ['cd'],
    ['fan'],
    ['makeup'],
    ['moscow'],
    ['tips'],
    ['build'],
    ['bt'],
    ['gal'],
    ['house'],
    ['parts'],
    ['place'],
    ['scot'],
    ['sex'],
    ['bot'],
    ['foundation'],
    ['audio'],
    ['gl'],
    ['mg'],
    ['pm'],
    ['tc'],
    ['town'],
    ['dog'],
    ['farm'],
    ['gallery'],
    ['business'],
    ['pet'],
    ['xin'],
    ['bn'],
    ['bw'],
    ['bzh'],
    ['delivery'],
    ['goog'],
    ['llc'],
    ['science'],
    ['cards'],
    ['gy'],
    ['nc'],
    ['nrw'],
    ['security'],
    ['tf'],
    ['jm'],
    ['menu'],
    ['pr'],
    ['style'],
    ['tg'],
    ['ye'],
    ['directory'],
    ['fo'],
    ['ml'],
    ['pictures'],
    ['bj'],
    ['as'],
    ['boats'],
    ['courses'],
    ['eco'],
    ['express'],
    ['fj'],
    ['garden'],
    ['lc'],
    ['partners'],
    ['wales'],
    ['clinic'],
    ['golf'],
    ['sale'],
    ['va'],
    ['bi'],
    ['coffee'],
    ['horse'],
    ['nyc'],
    ['vu'],
    ['zip'],
    ['careers'],
    ['engineering'],
    ['tl'],
    ['estate'],
    ['gay'],
    ['legal'],
    ['living'],
    ['movie'],
    ['sd'],
    ['vet'],
    ['crs'],
    ['green'],
    ['ht'],
    ['international'],
    ['london'],
    ['pg'],
    ['rent'],
    ['law'],
    ['radio'],
    ['sport'],
    ['wine'],
    ['auto'],
    ['bf'],
    ['bm'],
    ['church'],
    ['ga'],
    ['motorcycles'],
    ['museum'],
    ['photos'],
    ['pink'],
    ['tk'],
    ['vision'],
    ['wang'],
    ['brussels'],
    ['dad'],
    ['family'],
    ['ls'],
    ['pizza'],
    ['shopping'],
    ['cab'],
    ['capital'],
    ['fashion'],
    ['toys'],
    ['webcam'],
    ['black'],
    ['ceo'],
    ['institute'],
    ['je'],
    ['pf'],
    ['photo'],
    ['ax'],
    ['bayern'],
    ['dating'],
    ['deals'],
    ['film'],
    ['football'],
    ['gift'],
    ['promo'],
    ['university'],
    ['you'],
    ['yt'],
    ['auction'],
    ['fitness'],
    ['taxi'],
    ['wf'],
    ['free'],
    ['loan'],
    ['mr'],
    ['paris'],
    ['cg'],
    ['fund'],
    ['gmbh'],
    ['shoes'],
    ['bs'],
    ['computer'],
    ['cymru'],
    ['foo'],
    ['ist'],
    ['marketing'],
    ['observer'],
    ['reviews'],
    ['sm'],
    ['tax'],
    ['xn--6frz82g', '移动'],
    ['band'],
    ['basketball'],
    ['camp'],
    ['doctor'],
    ['futbol'],
    ['gratis'],
    ['lifestyle'],
    ['ne'],
    ['sexy'],
    ['training'],
    ['boo'],
    ['camera'],
    ['dental'],
    ['gm'],
    ['gp'],
    ['hot'],
    ['how'],
    ['kiwi'],
    ['lgbt'],
    ['sz'],
    ['cw'],
    ['istanbul'],
    ['jetzt'],
    ['limited'],
    ['mc'],
    ['poker'],
    ['recipes'],
    ['rio'],
    ['ski'],
    ['sr'],
    ['supply'],
    ['actor'],
    ['army'],
    ['barcelona'],
    ['bible'],
    ['boutique'],
    ['cf'],
    ['christmas'],
    ['dance'],
    ['dm'],
    ['faith'],
    ['gi'],
    ['insure'],
    ['ki'],
    ['ky'],
    ['management'],
    ['mba'],
    ['new'],
    ['sb'],
    ['schule'],
    ['sl'],
    ['soccer'],
    ['xn--p1acf', 'рус'],
    ['yoga'],
    ['amsterdam'],
    ['college'],
    ['credit'],
    ['diet'],
    ['fail'],
    ['markets'],
    ['med'],
    ['meme'],
    ['quebec'],
    ['review'],
    ['taipei'],
    ['tattoo'],
    ['ventures'],
    ['xn--90ais', 'бел'],
    ['box'],
    ['coach'],
    ['dj'],
    ['locker'],
    ['mp'],
    ['nf'],
    ['ngo'],
    ['pn'],
    ['ren'],
    ['rentals'],
    ['saarland'],
    ['spot'],
    ['fish'],
    ['immo'],
    ['koeln'],
    ['luxury'],
    ['mobile'],
    ['rugby'],
    ['sarl'],
    ['solar'],
    ['tours'],
    ['xn--80asehdb', 'онлайн'],
    ['bb'],
    ['bingo'],
    ['coupons'],
    ['gifts'],
    ['glass'],
    ['hamburg'],
    ['kitchen'],
    ['krd'],
    ['td'],
    ['trading'],
    ['vegas'],
    ['wien'],
    ['adult'],
    ['boston'],
    ['broker'],
    ['charity'],
    ['clothing'],
    ['corsica'],
    ['discount'],
    ['enterprises'],
    ['financial'],
    ['forex'],
    ['gdn'],
    ['gives'],
    ['haus'],
    ['healthcare'],
    ['irish'],
    ['limo'],
    ['navy'],
    ['nr'],
    ['racing'],
    ['reisen'],
    ['spa'],
    ['tatar'],
    ['vlaanderen'],
    ['yokohama'],
    ['aw'],
    ['builders'],
    ['car'],
    ['cars'],
    ['cheap'],
    ['cricket'],
    ['engineer'],
    ['equipment'],
    ['forsale'],
    ['frl'],
    ['furniture'],
    ['gq'],
    ['kids'],
    ['lr'],
    ['moda'],
    ['mq'],
    ['restaurant'],
    ['storage'],
    ['tennis'],
    ['versicherung'],
    ['deal'],
    ['exposed'],
    ['fast'],
    ['gn'],
    ['investments'],
    ['kaufen'],
    ['nagoya'],
    ['photography'],
    ['post'],
    ['properties'],
    ['realestate'],
    ['repair'],
    ['republican'],
    ['rich'],
    ['salon'],
    ['soy'],
    ['supplies'],
    ['vote'],
    ['wedding'],
    ['xn--3e0b707e', '한국'],
    ['xn--80ao21a', 'қаз'],
    ['xn--mk1bu44c', '닷컴'],
    ['ck'],
    ['consulting'],
    ['contact'],
    ['diamonds'],
    ['flights'],
    ['flowers'],
    ['giving'],
    ['gripe'],
    ['gw'],
    ['hm'],
    ['industries'],
    ['jewelry'],
    ['lighting'],
    ['luxe'],
    ['meet'],
    ['realtor'],
    ['ruhr'],
    ['ss'],
    ['vi'],
    ['villas'],
    ['alsace'],
    ['associates'],
    ['capetown'],
    ['career'],
    ['catering'],
    ['channel'],
    ['claims'],
    ['cleaning'],
    ['cooking'],
    ['country'],
    ['cruises'],
    ['gf'],
    ['gle'],
    ['globo'],
    ['hockey'],
    ['holdings'],
    ['immobilien'],
    ['kp'],
    ['kyoto'],
    ['melbourne'],
    ['miami'],
    ['moi'],
    ['mortgage'],
    ['organic'],
    ['pharmacy'],
    ['property'],
    ['srl'],
    ['tickets'],
    ['tienda'],
    ['tirol'],
    ['voto'],
    ['voyage'],
    ['xn--h2brj9c', 'भारत'],
    ['xn--j1amh', 'укр'],
    ['xn--t60b56a', '닷넷'],
    ['aq'],
    ['archi'],
    ['construction'],
    ['durban'],
    ['esq'],
    ['fishing'],
    ['gent'],
    ['graphics'],
    ['guitars'],
    ['hiphop'],
    ['holiday'],
    ['joburg'],
    ['kn'],
    ['kred'],
    ['loans'],
    ['music'],
    ['pay'],
    ['physio'],
    ['plumbing'],
    ['select'],
    ['shiksha'],
    ['singles'],
    ['sucks'],
    ['tires'],
    ['vodka'],
    ['xn--c1avg', 'орг'],
    ['xn--d1acj3b', 'дети'],
    ['xn--fiqs8s', '中国'],
    ['abogado'],
    ['abudhabi'],
    ['airforce'],
    ['apartments'],
    ['bargains'],
    ['cologne'],
    ['compare'],
    ['condos'],
    ['contractors'],
    ['creditcard'],
    ['dealer'],
    ['democrat'],
    ['fk'],
    ['florist'],
    ['gop'],
    ['insurance'],
    ['km'],
    ['latino'],
    ['lawyer'],
    ['lease'],
    ['ltda'],
    ['maison'],
    ['osaka'],
    ['phd'],
    ['play'],
    ['politie'],
    ['productions'],
    ['protection'],
    ['reise'],
    ['rsvp'],
    ['stockholm'],
    ['surgery'],
    ['talk'],
    ['theater'],
    ['vacations'],
    ['xn--80adxhks', 'москва'],
    ['xn--ngbc5azd', 'شبكة'],
    ['accountant'],
    ['accountants'],
    ['akdn'],
    ['allfinanz'],
    ['analytics'],
    ['attorney'],
    ['author'],
    ['blackfriday'],
    ['book'],
    ['broadway'],
    ['buy'],
    ['call'],
    ['cpa'],
    ['degree'],
    ['dentist'],
    ['er'],
    ['feedback'],
    ['ftr'],
    ['got'],
    ['hospital'],
    ['ismaili'],
    ['joy'],
    ['juegos'],
    ['like'],
    ['llp'],
    ['madrid'],
    ['memorial'],
    ['office'],
    ['okinawa'],
    ['ong'],
    ['pin'],
    ['read'],
    ['realty'],
    ['rehab'],
    ['reit'],
    ['room'],
    ['ryukyu'],
    ['safe'],
    ['samsung'],
    ['save'],
    ['secure'],
    ['smile'],
    ['stc'],
    ['sydney'],
    ['trust'],
    ['viajes'],
    ['voting'],
    ['watches'],
    ['wow'],
    ['xn--2scrj9c', 'ಭಾರತ'],
    ['xn--4dbrk0ce', 'ישראל'],
    ['xn--55qx5d', '公司'],
    ['xn--5tzm5g', '网站'],
    ['xn--80aswg', 'сайт'],
    ['xn--90ae', 'бг'],
    ['xn--9dbq2a', 'קום'],
    ['xn--czrs0t', '商店'],
    ['xn--fpcrj9c3d', 'భారత్'],
    ['xn--io0a7i', '网络'],
    ['xn--node', 'გე'],
    ['xn--q9jyb4c', 'みんな'],
    ['xn--ses554g', '网址'],
    ['xn--unup4y', '游戏'],
    ['xn--vhquv', '企业'],
    ['xn--vuq861b', '信息'],
    ['xn--xkc2dl3a5ee0h', 'இந்தியா'],
    ['xn--zfr164b', '政务'],
    ['yamaxun'],
    ['zero'],
    ['zuerich'],
    ['able'],
    ['ads'],
    ['agakhan'],
    ['anquan'],
    ['arab'],
    ['aramco'],
    ['baidu'],
    ['baseball'],
    ['bcn'],
    ['bom'],
    ['booking'],
    ['bv'],
    ['cal'],
    ['catholic'],
    ['circle'],
    ['comsec'],
    ['coupon'],
    ['creditunion'],
    ['cruise'],
    ['data'],
    ['dclk'],
    ['dds'],
    ['docs'],
    ['dot'],
    ['drive'],
    ['dtv'],
    ['dubai'],
    ['dvr'],
    ['eat'],
    ['erni'],
    ['final'],
    ['firmdale'],
    ['fly'],
    ['gb'],
    ['gbiz'],
    ['ggee'],
    ['grocery'],
    ['gu'],
    ['guge'],
    ['hangout'],
    ['helsinki'],
    ['here'],
    ['hiv'],
    ['hotels'],
    ['imamat'],
    ['jot'],
    ['jprs'],
    ['kerryhotels'],
    ['kerryproperties'],
    ['kfh'],
    ['kosher'],
    ['kuokgroup'],
    ['lacaixa'],
    ['lasalle'],
    ['lifeinsurance'],
    ['lotto'],
    ['mango'],
    ['map'],
    ['merck'],
    ['merckmsd'],
    ['mh'],
    ['mls'],
    ['mma'],
    ['olayan'],
    ['olayangroup'],
    ['ollo'],
    ['ott'],
    ['phone'],
    ['pid'],
    ['pohl'],
    ['prod'],
    ['prof'],
    ['redumbrella'],
    ['richardli'],
    ['safety'],
    ['sakura'],
    ['scholarships'],
    ['search'],
    ['shouji'],
    ['sj'],
    ['sohu'],
    ['song'],
    ['star'],
    ['stcgroup'],
    ['thd'],
    ['theatre'],
    ['travelersinsurance'],
    ['trv'],
    ['tunes'],
    ['tushu'],
    ['tvs'],
    ['vana'],
    ['viva'],
    ['wanggou'],
    ['weather'],
    ['web'],
    ['weibo'],
    ['whoswho'],
    ['xihuan'],
    ['xn--11b4c3d', 'कॉम'],
    ['xn--1ck2e1b', 'セール'],
    ['xn--1qqw23a', '佛山'],
    ['xn--30rr7y', '慈善'],
    ['xn--3bst00m', '集团'],
    ['xn--3ds443g', '在线'],
    ['xn--3hcrj9c', 'ଭାରତ'],
    ['xn--3pxu8k', '点看'],
    ['xn--42c2d9a', 'คอม'],
    ['xn--45br5cyl', 'ভাৰত'],
    ['xn--45brj9c', 'ভারত'],
    ['xn--45q11c', '八卦'],
    ['xn--4gbrim', 'موقع'],
    ['xn--54b7fta0cc', 'বাংলা'],
    ['xn--55qw42g', '公益'],
    ['xn--6qq986b3xl', '我爱你'],
    ['xn--80aqecdr1a', 'католик'],
    ['xn--90a3ac', 'срб'],
    ['xn--9et52u', '时尚'],
    ['xn--bck1b9a5dre4c', 'ファッション'],
    ['xn--c2br7g', 'नेट'],
    ['xn--cck2b3b', 'ストア'],
    ['xn--cg4bki', '삼성'],
    ['xn--clchc0ea0b2g2a9gcd', 'சிங்கப்பூர்'],
    ['xn--czr694b', '商标'],
    ['xn--czru2d', '商城'],
    ['xn--d1alf', 'мкд'],
    ['xn--e1a4c', 'ею'],
    ['xn--eckvdtc9d', 'ポイント'],
    ['xn--efvy88h', '新闻'],
    ['xn--fct429k', '家電'],
    ['xn--fhbei', 'كوم'],
    ['xn--fiq228c5hs', '中文网'],
    ['xn--fiqz9s', '中國'],
    ['xn--fjq720a', '娱乐'],
    ['xn--fzc2c9e2c', 'ලංකා'],
    ['xn--g2xx48c', '购物'],
    ['xn--gckr3f0f', 'クラウド'],
    ['xn--gecrj9c', 'ભારત'],
    ['xn--gk3at1e', '通販'],
    ['xn--h2breg3eve', 'भारतम्'],
    ['xn--h2brj9c8c', 'भारोत'],
    ['xn--hxt814e', '网店'],
    ['xn--i1b6b1a6a2e', 'संगठन'],
    ['xn--imr513n', '餐厅'],
    ['xn--j1aef', 'ком'],
    ['xn--j6w193g', '香港'],
    ['xn--jvr189m', '食品'],
    ['xn--kprw13d', '台湾'],
    ['xn--kpry57d', '台灣'],
    ['xn--kput3i', '手机'],
    ['xn--l1acc', 'мон'],
    ['xn--lgbbat1ad8j', 'الجزائر'],
    ['xn--mgb9awbf', 'عمان'],
    ['xn--mgba3a3ejt', 'ارامكو'],
    ['xn--mgba3a4f16a', 'ایران'],
    ['xn--mgba7c0bbn0a', 'العليان'],
    ['xn--mgbaam7a8h', 'امارات'],
    ['xn--mgbab2bd', 'بازار'],
    ['xn--mgbah1a3hjkrd', 'موريتانيا'],
    ['xn--mgbai9azgqp6j', 'پاکستان'],
    ['xn--mgbayh7gpa', 'الاردن'],
    ['xn--mgbbh1a', 'بارت'],
    ['xn--mgbbh1a71e', 'بھارت'],
    ['xn--mgbc0a9azcg', 'المغرب'],
    ['xn--mgbca7dzdo', 'ابوظبي'],
    ['xn--mgbcpq6gpa1a', 'البحرين'],
    ['xn--mgberp4a5d4ar', 'السعودية'],
    ['xn--mgbgu82a', 'ڀارت'],
    ['xn--mgbi4ecexp', 'كاثوليك'],
    ['xn--mgbpl2fh', 'سودان'],
    ['xn--mgbtx2b', 'عراق'],
    ['xn--mgbx4cd0ab', 'مليسيا'],
    ['xn--mix891f', '澳門'],
    ['xn--mxtq1m', '政府'],
    ['xn--ngbe9e0a', 'بيتك'],
    ['xn--ngbrx', 'عرب'],
    ['xn--nqv7f', '机构'],
    ['xn--nqv7fs00ema', '组织机构'],
    ['xn--nyqy26a', '健康'],
    ['xn--o3cw4h', 'ไทย'],
    ['xn--ogbpf8fl', 'سورية'],
    ['xn--otu796d', '招聘'],
    ['xn--pgbs0dh', 'تونس'],
    ['xn--pssy2u', '大拿'],
    ['xn--q7ce6a', 'ລາວ'],
    ['xn--qcka1pmc', 'グーグル'],
    ['xn--qxa6a', 'ευ'],
    ['xn--qxam', 'ελ'],
    ['xn--rhqv96g', '世界'],
    ['xn--rovu88b', '書籍'],
    ['xn--rvc1e0am3e', 'ഭാരതം'],
    ['xn--s9brj9c', 'ਭਾਰਤ'],
    ['xn--tckwe', 'コム'],
    ['xn--tiq49xqyj', '天主教'],
    ['xn--vermgensberater-ctb', 'vermögensberater'],
    ['xn--vermgensberatung-pwb', 'vermögensberatung'],
    ['xn--w4r85el8fhu5dnra', '嘉里大酒店'],
    ['xn--wgbh1c', 'مصر'],
    ['xn--wgbl6a', 'قطر'],
    ['xn--xhq521b', '广东'],
    ['xn--xkc2al3hye2a', 'இலங்கை'],
    ['xn--y9a3aq', 'հայ'],
    ['xn--yfro4i67o', '新加坡'],
    ['xn--ygbi2ammx', 'فلسطين'],
    ['yun']
];

const KNOWN = new Set(ALL_TLDS.map(([tld]) => tld));

/** Is this a top-level domain somebody could actually buy? */
export function isTld(value: string): boolean {
    return KNOWN.has(value);
}
